/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ticTacToe;


import javax.swing.JOptionPane;

/**
 *
 * @author duong
 */
public class ticTacToe extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ticTacToe.class.getName());
    String[] board = new String[10];
    int luot = 0;
    public String turn() {
        if(luot==0){
            return "X";
        }else{
            return "O";
        }
}   
    public void clear(){
        for (int i = 0; i < board.length; i++) {
        board[i] = null;
        }
        // Reset text của các nút
        jButton1.setText("");
        jButton2.setText("");
        jButton3.setText("");
        jButton4.setText("");
        jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");
        jButton9.setText("");
        resutls.setText("");
    }
    public boolean checkWinner(){
    String winner = null;
    int[][] winConditions = {
        {1, 2, 3}, // Hàng ngang trên: board[1] (jButton4), board[2] (jButton1), board[3] (jButton2)
        {4, 5, 6}, // Hàng ngang giữa: board[4] (jButton7), board[5] (jButton6), board[6] (jButton5)
        {7, 8, 9}, // Hàng ngang dưới: board[7] (jButton3), board[8] (jButton8), board[9] (jButton9)
        {1, 4, 7}, // Hàng dọc 1
        {2, 5, 8}, // Hàng dọc 2
        {3, 6, 9}, // Hàng dọc 3
        {1, 5, 9}, // Đường chéo chính
        {3, 5, 7}  // Đường chéo phụ
    };

    for (int[] condition : winConditions) {
        String cell1 = board[condition[0]];
        String cell2 = board[condition[1]];
        String cell3 = board[condition[2]];
        
        // Chỉ kiểm tra nếu cả 3 ô đều đã được đánh (không phải null)
        if (cell1 != null && cell1.equals(cell2) && cell1.equals(cell3)) {
            winner = cell1;
            break; 
        }
    }

    if (winner != null) {
        // Có người thắng
        JOptionPane.showMessageDialog(this, winner + " thang!");
        resutls.setText(winner + " thang! Nhan START de choi lai.");
        clear();
        return true;
    } 

    // Kiểm tra hòa (nếu không có người thắng và tất cả 9 ô đã được điền)
    int count = 0;
    for (int i = 1; i <= 9; i++) {
        if (board[i] != null && (board[i].equals("X") || board[i].equals("O"))) {
            count++;
        }
    }

    if (count == 9) {
        // Bàn cờ đầy, không có người thắng -> Hòa
        JOptionPane.showMessageDialog(this, "Hoa!");
        resutls.setText("Hoa! Nhan START de choi lai.");
        clear();
        return true;
    }
    
    // Trò chơi tiếp tục
    return false;
}
    /**
     * Creates new form ticTacToe
     */
    public ticTacToe() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        startBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        resutls = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);

        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Tic Tac Toe");

        startBtn.setText("Start");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridLayout());

        resutls.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(resutls);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(startBtn)
                        .addGap(0, 155, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                            .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(startBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        // TODO add your handling code here:
        luot = 0;
        clear();
        resutls.setText("Toi luot cua " + turn() + ". Vui long chon o!");
    }//GEN-LAST:event_startBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(jButton4.getText().isEmpty()&& !resutls.getText().isEmpty()){
            jButton4.setText(turn());
            board[1]= jButton4.getText();
            if (checkWinner() == false) { 
            // 3. Nếu CHƯA có người thắng/hòa, thì chuyển lượt
            if(luot == 0){
                luot = 1;
            }else{
                luot = 0;
            }
            resutls.setText("Toi luot cua " + turn() + ". Vui long chon o!");
        }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jButton1.getText().isEmpty()&& !resutls.getText().isEmpty()){
            jButton1.setText(turn());
            board[2]= jButton1.getText();
            if (checkWinner() == false) { 
            // 3. Nếu CHƯA có người thắng/hòa, thì chuyển lượt
            if(luot == 0){
                luot = 1;
            }else{
                luot = 0;
            }
            resutls.setText("Toi luot cua " + turn() + ". Vui long chon o!");
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jButton2.getText().isEmpty()&& !resutls.getText().isEmpty()){
            jButton2.setText(turn());
            board[3]= jButton2.getText();
            if (checkWinner() == false) { 
            // 3. Nếu CHƯA có người thắng/hòa, thì chuyển lượt
            if(luot == 0){
                luot = 1;
            }else{
                luot = 0;
            }
            resutls.setText("Toi luot cua " + turn() + ". Vui long chon o!");
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(jButton7.getText().isEmpty()&& !resutls.getText().isEmpty()){
            jButton7.setText(turn());
            board[4]= jButton7.getText();
            if (checkWinner() == false) { 
            // 3. Nếu CHƯA có người thắng/hòa, thì chuyển lượt
            if(luot == 0){
                luot = 1;
            }else{
                luot = 0;
            }
            resutls.setText("Toi luot cua " + turn() + ". Vui long chon o!");
        }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(jButton6.getText().isEmpty()&& !resutls.getText().isEmpty()){
            jButton6.setText(turn());
            board[5]= jButton6.getText();
            if (checkWinner() == false) { 
            // 3. Nếu CHƯA có người thắng/hòa, thì chuyển lượt
            if(luot == 0){
                luot = 1;
            }else{
                luot = 0;
            }
            resutls.setText("Toi luot cua " + turn() + ". Vui long chon o!");
        }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(jButton5.getText().isEmpty()&& !resutls.getText().isEmpty()){
            jButton5.setText(turn());
            board[6]= jButton5.getText();
            if (checkWinner() == false) { 
            // 3. Nếu CHƯA có người thắng/hòa, thì chuyển lượt
            if(luot == 0){
                luot = 1;
            }else{
                luot = 0;
            }
            resutls.setText("Toi luot cua " + turn() + ". Vui long chon o!");
        }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jButton3.getText().isEmpty()&& !resutls.getText().isEmpty()){
            jButton3.setText(turn());
            board[7]= jButton3.getText();
            if (checkWinner() == false) { 
            // 3. Nếu CHƯA có người thắng/hòa, thì chuyển lượt
            if(luot == 0){
                luot = 1;
            }else{
                luot = 0;
            }
            resutls.setText("Toi luot cua " + turn() + ". Vui long chon o!");
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(jButton8.getText().isEmpty()&& !resutls.getText().isEmpty()){
            jButton8.setText(turn());
            board[8]= jButton8.getText();
            if (checkWinner() == false) { 
            // 3. Nếu CHƯA có người thắng/hòa, thì chuyển lượt
            if(luot == 0){
                luot = 1;
            }else{
                luot = 0;
            }
            resutls.setText("Toi luot cua " + turn() + ". Vui long chon o!");
        }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(jButton9.getText().isEmpty()&& !resutls.getText().isEmpty()){
            jButton9.setText(turn());
            board[9]= jButton9.getText();
            if (checkWinner() == false) { 
            // 3. Nếu CHƯA có người thắng/hòa, thì chuyển lượt
            if(luot == 0){
                luot = 1;
            }else{
                luot = 0;
            }
            resutls.setText("Toi luot cua " + turn() + ". Vui long chon o!");
        }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ticTacToe().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel resutls;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables
}
