/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniBank;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLIntegrityConstraintViolationException;
import javax.swing.JOptionPane;

/**
 *
 * @author duong
 */
public class signUpDisplay extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(signUpDisplay.class.getName());
    private static final int NULL = 0;
    static Connection con = connection.getConnection();
    
    /**
     * Creates new form mainDisplay
     */
    public signUpDisplay() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        signUpBtn = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MiniBank");

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));
        jPanel1.add(jTextField1);
        jPanel1.add(jPasswordField1);
        jPanel1.add(jPasswordField2);

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setText("User name:");
        jPanel2.add(jLabel1);

        jLabel2.setText("Password:");
        jPanel2.add(jLabel2);

        jLabel3.setText("Confirm PW:");
        jPanel2.add(jLabel3);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        signUpBtn.setText("Sign Up");
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });
        jPanel3.add(signUpBtn);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel3.add(Back);

        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Sign up page");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        new logDisplay().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        String user = jTextField1.getText().trim(); // Dùng trim() để loại bỏ khoảng trắng dư thừa
    char[] pwChars = jPasswordField1.getPassword();
    char[] cfpwChars = jPasswordField2.getPassword();
    String pw = new String(pwChars);
    String cfpw = new String(cfpwChars);
    
    // Đảm bảo mảng char[] được xóa sau khi dùng
    PreparedStatement ps = null;
    
    try {
        // 1. Kiểm tra rỗng (SỬA LỖI: dùng &&)
        if (user.isEmpty() || pw.isEmpty() || cfpw.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!");
            return; // Dừng lại nếu có trường rỗng
        }
        
        // 2. Kiểm tra xác nhận mật khẩu
        if (!pw.equals(cfpw)) {
            JOptionPane.showMessageDialog(this, 
                    "The confirm password does not match!", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            // Xóa nội dung hai trường mật khẩu để người dùng nhập lại
            jPasswordField1.setText("");
            jPasswordField2.setText("");
            return; // Dừng lại nếu mật khẩu không khớp
        } 
        
        // 3. Thực hiện INSERT (Sử dụng Hashing nếu có thể)
        String sql = "INSERT INTO customer(cname, balance, pass_code) VALUES (?, 1000, ?)";
        ps = con.prepareStatement(sql);
        ps.setString(1, user);
        // LƯU Ý BẢO MẬT: BẠN CẦN BĂM (HASH) MẬT KHẨU Ở ĐÂY
        ps.setString(2, pw); // Tạm thời dùng plaintext, nhưng cần BĂM!
        
        int rows = ps.executeUpdate();

        if (rows == 1) {
            JOptionPane.showMessageDialog(this, "Successfully!");
            new logDisplay().setVisible(true);
            dispose();
        } else {
             // Trường hợp hiếm khi executeUpdate trả về 0 mà không ném exception
             JOptionPane.showMessageDialog(this, "Register succesfully!");
        }

    } catch (SQLIntegrityConstraintViolationException e) {
        // Xử lý username đã tồn tại
        JOptionPane.showMessageDialog(this, "Username already exists! Try another one.");
    } catch (Exception e) {
        // Xử lý các lỗi khác (lỗi kết nối, lỗi SQL syntax...)
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Sign Up Error");
    } finally {
        // RẤT QUAN TRỌNG: Xóa mật khẩu khỏi bộ nhớ
        java.util.Arrays.fill(pwChars, '0');
        java.util.Arrays.fill(cfpwChars, '0');
        
        // Đóng PreparedStatement nếu có thể
        if (ps != null) {
            try {
                ps.close();
            } catch (Exception e) {
                logger.log(java.util.logging.Level.SEVERE, null, e);
            }
        }
    }
    }//GEN-LAST:event_signUpBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new signUpDisplay().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton signUpBtn;
    // End of variables declaration//GEN-END:variables
}
