/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniBank;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author duong
 */
public class transferForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(transferForm.class.getName());
    private int loggedInAcNo; 
    static Connection con = connection.getConnection();
    /**
     * Creates new form NewJFrame
     */
    public transferForm(int acNo) {
        this.loggedInAcNo = acNo;
        initComponents();
        loadCustomerInfo();
        adID.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            adIDFocusLost(evt);
            }
        });
    }
    public transferForm() {
        initComponents();
    }
    private void loadCustomerInfo() {
        String sql = "SELECT cname, balance FROM customer WHERE ac_no = ?";
        
        try (java.sql.PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1, this.loggedInAcNo);
            
            try (java.sql.ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    String name = rs.getString("cname");
                    int balance = rs.getInt("balance");
                    userName.setText(name);
                    balancefields.setText(""+balance+"");
                }
            }
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error when loading customer infor!");
        }
    }
    private void loadReceiverName(int receiverAcNo) {
    // Tránh truy vấn nếu ID là của người gửi
    if (receiverAcNo == this.loggedInAcNo) {
        nameTransfer.setText("Your account");
        return;
    }
    
    String sql = "SELECT cname FROM customer WHERE ac_no = ?";
    
    try (PreparedStatement ps = con.prepareStatement(sql)) {
        ps.setInt(1, receiverAcNo);
        
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                String name = rs.getString("cname");
                // Tự động điền tên vào trường nameTransfer
                nameTransfer.setText(name); 
            } else {
                // Nếu không tìm thấy ID
                nameTransfer.setText("Invalid account!");
            }
        }
    } catch (SQLException e) {
        // Log lỗi hoặc hiển thị thông báo nhẹ
        logger.log(java.util.logging.Level.SEVERE, "Error loading receiver name", e);
        nameTransfer.setText("Error DB");
    } catch (NumberFormatException e) {
        // Xử lý nếu adID có chữ (mặc dù nên dùng DocumentFilter để cấm chữ)
        nameTransfer.setText("Invaild ID");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        confirmBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        balancefields = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ac_NoTitle = new javax.swing.JLabel();
        adID = new javax.swing.JTextField();
        nameTitle = new javax.swing.JLabel();
        nameTransfer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        moneyTrans = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MiniBank");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });
        jPanel1.add(confirmBtn);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        Title.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        Title.setText("Sender Infor");
        Title.setToolTipText("");

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setText("Name :");
        jPanel2.add(jLabel1);

        userName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userName.setText("customer!");
        jPanel2.add(userName);
        jPanel2.add(jLabel3);

        jLabel2.setText("Balance :");
        jPanel2.add(jLabel2);

        balancefields.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        balancefields.setText("*******");
        jPanel2.add(balancefields);
        jPanel2.add(jLabel4);

        jPanel3.setLayout(new java.awt.GridLayout(0, 2));

        ac_NoTitle.setText("Receiver ID :");
        jPanel3.add(ac_NoTitle);

        adID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                adIDFocusLost(evt);
            }
        });
        jPanel3.add(adID);

        nameTitle.setText("Name :");
        jPanel3.add(nameTitle);
        jPanel3.add(nameTransfer);

        jLabel6.setText("Money :");
        jPanel3.add(jLabel6);
        jPanel3.add(moneyTrans);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 14)); // NOI18N
        jLabel5.setText("Receiver Infor ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new mainDisplay(loggedInAcNo).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // 1. Lấy dữ liệu từ các trường nhập liệu
        String receiverAcStr = adID.getText().trim();
        String amountStr = moneyTrans.getText().trim();

    // Khởi tạo các biến số cần thiết
        int sender_ac = loggedInAcNo;
        int receiver_ac;
        int amount;
    
    // 2. Kiểm tra Rỗng và Chuyển đổi String sang int
        if (receiverAcStr.isEmpty() || amountStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Invaild input", JOptionPane.WARNING_MESSAGE);
            return;
        }
    
        try {
        // Chuyển đổi ID người nhận
            receiver_ac = Integer.parseInt(receiverAcStr);
        // Chuyển đổi Số tiền
            amount = Integer.parseInt(amountStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                                      "Account or amount not availble!. Try again",
                                      "Error format", 
                                      JOptionPane.ERROR_MESSAGE);
            return; // Dừng nếu nhập không phải số
        }
    
    // 3. Kiểm tra logic nghiệp vụ cơ bản
        if (amount <= 0) {
            JOptionPane.showMessageDialog(this, "Amount shoud be more than 0.", "Error transfer", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (receiver_ac == sender_ac) {
            JOptionPane.showMessageDialog(this, "Can't transfer your own account", "Error transfer", JOptionPane.WARNING_MESSAGE);
            return;
        }
            try {
        con.setAutoCommit(false); // Vô hiệu hóa auto-commit
        
        // 4. Kiểm tra số dư người gửi và sự tồn tại của người nhận
        // Truy vấn này đồng thời kiểm tra số dư và đảm bảo người nhận tồn tại
        String checkData = "SELECT balance FROM customer WHERE ac_no = ?";
        
        // Kiểm tra người gửi (số dư)
        PreparedStatement psSender = con.prepareStatement(checkData);
        psSender.setInt(1, sender_ac);
        ResultSet rsSender = psSender.executeQuery();
        
        if (!rsSender.next()) {
             JOptionPane.showMessageDialog(this, "Error : Can't find sender account", "Error system", JOptionPane.ERROR_MESSAGE);
             con.rollback(); 
             return;
        }
        int senderBalance = rsSender.getInt("balance");
        rsSender.close();
        psSender.close();

        if (senderBalance < amount) {
            JOptionPane.showMessageDialog(this, "Balance is not enough to trace");
            con.rollback(); 
            return;
        }

        // Kiểm tra người nhận (đảm bảo tồn tại)
        PreparedStatement psReceiver = con.prepareStatement(checkData);
        psReceiver.setInt(1, receiver_ac);
        ResultSet rsReceiver = psReceiver.executeQuery();
        if (!rsReceiver.next()) {
            JOptionPane.showMessageDialog(this, "Can't found this ID (ID: " + receiver_ac + ").", "Error account!", JOptionPane.WARNING_MESSAGE);
            con.rollback();
            return;
        }
        rsReceiver.close();
        psReceiver.close();

        // 5. Thực hiện giao dịch (Debit & Credit)
        
        // 5a. Trừ tiền người gửi
        String debit = "UPDATE customer SET balance = balance - ? WHERE ac_no = ?";
        PreparedStatement psDebit = con.prepareStatement(debit);
        psDebit.setInt(1, amount);
        psDebit.setInt(2, sender_ac);
        psDebit.executeUpdate();
        psDebit.close();

        // 5b. Cộng tiền người nhận
        String credit = "UPDATE customer SET balance = balance + ? WHERE ac_no = ?";
        PreparedStatement psCredit = con.prepareStatement(credit);
        psCredit.setInt(1, amount);
        psCredit.setInt(2, receiver_ac);
        psCredit.executeUpdate();
        psCredit.close();
        
        // 6. Hoàn tất và thông báo
        con.commit(); // Hoàn tất transaction
        JOptionPane.showMessageDialog(this, "Transfer Succesfully! ", "Succesful", JOptionPane.INFORMATION_MESSAGE);
        
        // Quay về màn hình chính
        new mainDisplay(loggedInAcNo).setVisible(true);
        dispose();
        
    } catch (SQLException e) {
        // Xử lý lỗi Transaction
        try {
            con.rollback(); // Hoàn tác nếu có lỗi
            JOptionPane.showMessageDialog(this, "Error : Cancel trace !", "Error SQL", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Rollback failed", ex);
            JOptionPane.showMessageDialog(this, "Hard error system ", "Hard Error", JOptionPane.ERROR_MESSAGE);
        }
        logger.log(java.util.logging.Level.SEVERE, "Transaction error", e);
    } finally {
        // Thiết lập lại auto-commit
        try {
            con.setAutoCommit(true);
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Failed to reset auto-commit", ex);
        }
    }
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void adIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adIDFocusLost
        // TODO add your handling code here:
        String receiverAcStr = adID.getText().trim();

    if (receiverAcStr.isEmpty()) {
        nameTransfer.setText("");
        return;
    }
    
    try {
        // Chuyển đổi String sang int
        int receiverAcNo = Integer.parseInt(receiverAcStr); 
        
        // Gọi hàm truy vấn và điền tên
        loadReceiverName(receiverAcNo);
        
    } catch (NumberFormatException e) {
        // Xử lý lỗi nếu người dùng nhập ký tự không phải số
        nameTransfer.setText("Invaild ID");
    }
    }//GEN-LAST:event_adIDFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new transferForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel ac_NoTitle;
    private javax.swing.JTextField adID;
    private javax.swing.JLabel balancefields;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField moneyTrans;
    private javax.swing.JLabel nameTitle;
    private javax.swing.JTextField nameTransfer;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
